#!/usr/bin/env python3
"""
PlumberBench CLI Submission Tool
Usage:
    python3 scripts/submit.py \
      --file path/to/mario.html \
      --id model_name \
      --title "Display Name" \
      --author "Your Handle" \
      --model "Model Name" \
      --hardware "RTX 4090 24GB" \
      --source "https://reddit.com/r/..." \
      --prompt "Write a complete Mario clone..."
"""

import argparse
import json
import os
import shutil
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_JSON_PATH = os.path.join(REPO_ROOT, "data.json")
GAMES_DIR = os.path.join(REPO_ROOT, "games")
PREVIEWS_DIR = os.path.join(REPO_ROOT, "previews")

def main():
    parser = argparse.ArgumentParser(description="Submit a new one-shot retro arcade/retro game to PlumberBench")
    parser.add_argument("--file", required=True, help="Path to raw, unedited HTML game file")
    parser.add_argument("--id", required=True, help="Unique identifier (e.g. claude35_sonnet_plumber)")
    parser.add_argument("--title", required=True, help="Game display title (do not include trademarked names)")
    parser.add_argument("--genre", choices=["platformer", "raycaster", "maze", "puzzle"], default="platformer", help="Discipline / Genre: platformer | raycaster | maze | puzzle")
    parser.add_argument("--author", required=True, help="Author name or Reddit handle")
    parser.add_argument("--model", required=True, help="Model identifier (e.g. Qwen3.8-Flash-Next)")
    parser.add_argument("--harness", default="llama.cpp", help="Harness / Inference Engine (e.g. llama.cpp, vLLM, Frontier API)")
    parser.add_argument("--effort", default="Single Turn One-Shot", help="Thinking / Reasoning Effort (e.g. 10k CoT Budget, High Reasoning, Full Deliberation)")
    parser.add_argument("--hardware", required=True, help="Hardware platform or Cloud API (e.g. RTX 4090 24GB, Cloud API)")
    parser.add_argument("--source", required=True, help="Source URL (Reddit post, GitHub repo, etc.)")
    parser.add_argument("--prompt", required=True, help="Exact prompt fed to the model")
    parser.add_argument("--category", default="NES Purist", help="Category: NES Purist | Modern Indie | Reskin | 3D Raycaster")
    parser.add_argument("--badge", default="Community Submission", help="Short highlight badge")
    parser.add_argument("--demo", default="", help="Optional live web demo URL")
    parser.add_argument("--vibe", type=float, default=8.5, help="Subjective vibe score (1.0 - 10.0)")

    args = parser.parse_args()

    if not os.path.exists(args.file):
        print(f"Error: File not found: {args.file}")
        sys.exit(1)

    os.makedirs(GAMES_DIR, exist_ok=True)
    os.makedirs(PREVIEWS_DIR, exist_ok=True)

    dest_filename = f"{args.id}.html"
    dest_path = os.path.join(GAMES_DIR, dest_filename)
    preview_filename = f"{args.id}.png"
    preview_path = os.path.join(PREVIEWS_DIR, preview_filename)

    print(f"1. Copying game file to {dest_path}...")
    shutil.copy2(args.file, dest_path)

    # Calculate file size and line count
    with open(dest_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = len(f.readlines())
    size_kb = round(os.path.getsize(dest_path) / 1024, 1)

    print("2. Generating high-resolution preview screenshot using headless browser...")
    prof_dir = f"/tmp/prof-submit-{args.id}"
    os.makedirs(prof_dir, exist_ok=True)
    firefox_cmd = [
        "firefox",
        "--headless",
        "--no-remote",
        "--profile", prof_dir,
        "--screenshot", preview_path,
        "--window-size=960,600",
        f"file://{os.path.abspath(dest_path)}"
    ]
    subprocess.run(firefox_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    if os.path.exists(preview_path):
        print(f"   ✓ Captured preview: {preview_path}")
    else:
        print(f"   ⚠️  Could not automatically capture preview. You can manually place an image at {preview_path}")

    # Build entry
    new_entry = {
        "id": args.id,
        "title": args.title,
        "genre": args.genre,
        "author": args.author,
        "category": args.category,
        "badge": args.badge,
        "file": f"games/{dest_filename}",
        "baseVotes": 0,
        "vibeScore": args.vibe,
        "size": f"{size_kb} KB",
        "lines": lines,
        "hardware": args.hardware,
        "model": args.model,
        "harness": args.harness,
        "thinkingEffort": args.effort,
        "mode": args.effort,
        "promptStyle": "Custom Zero-Shot",
        "prompt": args.prompt,
        "sourceName": "Community Submission",
        "sourceUrl": args.source,
        "vibeReview": f"One-shot {args.genre} generated by {args.model} via {args.harness} on {args.hardware}.",
        "ratings": {
            "nesCrunch": 8.0,
            "physicsFeel": 8.5,
            "ambition": 8.5
        },
        "elo": 1200,
        "matches": 0,
        "wins": 0,
        "preview": f"previews/{preview_filename}",
        "hidden": False
    }
    if args.demo:
        new_entry["demoUrl"] = args.demo

    print("3. Updating data.json...")
    with open(DATA_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Replace if exists, else append
    data = [x for x in data if x["id"] != args.id]
    data.append(new_entry)

    with open(DATA_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    print("4. Validating dataset integrity...")
    val_proc = subprocess.run([sys.executable, os.path.join(REPO_ROOT, "scripts", "validate.py")])
    if val_proc.returncode == 0:
        print("\n🎉 Submission successfully added and validated!")
        print(f"   Game ID: {args.id}")
        print(f"   Game File: games/{dest_filename}")
        print(f"   Preview: previews/{preview_filename}")
        print("\nNext step: Submit via Git:")
        print(f"   git checkout -b submit/{args.id}")
        print(f"   git add data.json games/{dest_filename} previews/{preview_filename}")
        print(f"   git commit -m 'feat: submit {args.model} {args.genre} game'")
    else:
        print("\n⚠️ Validation encountered warnings or errors. Check output above.")

if __name__ == "__main__":
    main()
